export type Pref = {
  id: number;
  name: string;
  area: string;
  population: number;
};
export const prefs = [
  { id: 1, name: "北海道", population: 5183, area: "北海道" },
  { id: 2, name: "青森県", population: 1221, area: "東北" },
  { id: 3, name: "岩手県", population: 1196, area: "東北" },
  { id: 4, name: "宮城県", population: 2290, area: "東北" },
  { id: 5, name: "秋田県", population: 945, area: "東北" },
  { id: 6, name: "山形県", population: 1055, area: "東北" },
  { id: 7, name: "福島県", population: 1812, area: "東北" },
  // { id: 8, name: "茨城県", population: 2852, area: "関東" },
  // { id: 9, name: "栃木県", population: 1921, area: "関東" },
  // { id: 10, name: "群馬県", population: 1927, area: "関東" },
  // { id: 11, name: "埼玉県", population: 7340, area: "関東" },
  // { id: 12, name: "千葉県", population: 6275, area: "関東" },
  // { id: 13, name: "東京都", population: 14010, area: "関東" },
  // { id: 14, name: "神奈川県", population: 9236, area: "関東" },
    // { id: 8, name: "茨城県", population: 2852, area: "関東" },
  { id: 9, name: "栃木県", population: 2000, area: "関東" },
  { id: 10, name: "群馬県", population: 2000, area: "関東" },
  { id: 11, name: "埼玉県", population: 6000, area: "関東" },
  { id: 12, name: "千葉県", population: 7000, area: "関東" },
  { id: 13, name: "東京都", population: 12000, area: "関東" },
  { id: 14, name: "神奈川県", population: 9000, area: "関東" },
  { id: 15, name: "新潟県", population: 2177, area: "中部" },
  { id: 16, name: "富山県", population: 1025, area: "中部" },
  { id: 17, name: "石川県", population: 1125, area: "中部" },
  { id: 18, name: "福井県", population: 760, area: "中部" },
  { id: 19, name: "山梨県", population: 805, area: "中部" },
  { id: 20, name: "長野県", population: 2033, area: "中部" },
  { id: 21, name: "岐阜県", population: 1961, area: "中部" },
  { id: 22, name: "静岡県", population: 3608, area: "中部" },
  { id: 23, name: "愛知県", population: 7517, area: "中部" },
  { id: 24, name: "三重県", population: 1756, area: "近畿" },
  { id: 25, name: "滋賀県", population: 1411, area: "近畿" },
  { id: 26, name: "京都府", population: 2561, area: "近畿" },
  { id: 27, name: "大阪府", population: 8806, area: "近畿" },
  { id: 28, name: "兵庫県", population: 5432, area: "近畿" },
  { id: 29, name: "奈良県", population: 1315, area: "近畿" },
  { id: 30, name: "和歌山県", population: 914, area: "近畿" },
  { id: 31, name: "鳥取県", population: 549, area: "中国" },
  { id: 32, name: "島根県", population: 665, area: "中国" },
  { id: 33, name: "岡山県", population: 1876, area: "中国" },
  { id: 34, name: "広島県", population: 2780, area: "中国" },
  { id: 35, name: "山口県", population: 1328, area: "中国" },
  { id: 36, name: "徳島県", population: 712, area: "四国" },
  { id: 37, name: "香川県", population: 942, area: "四国" },
  { id: 38, name: "愛媛県", population: 1321, area: "四国" },
  { id: 39, name: "高知県", population: 684, area: "四国" },
  { id: 40, name: "福岡県", population: 5124, area: "九州" },
  { id: 41, name: "佐賀県", population: 806, area: "九州" },
  { id: 42, name: "長崎県", population: 1297, area: "九州" },
  { id: 43, name: "熊本県", population: 1728, area: "九州" },
  { id: 44, name: "大分県", population: 1114, area: "九州" },
  { id: 45, name: "宮崎県", population: 1061, area: "九州" },
  { id: 46, name: "鹿児島県", population: 1576, area: "九州" },
  { id: 47, name: "沖縄県", population: 1468, area: "九州" },
];
