export const POLICY_PARAMS = {
  POINTS_FOR_BAR: 2,
  POINTS_FOR_VACCINE: 5,
  POINTS_FOR_FENCE: 5,
  POINTS_FOR_CURE_FASTER: 3,
};

export const EFFECT_PARAMS = {
  VACCINE_EFFECT: 0.7,
  CURE_FASTER_EFFECT: 0.6,
  CURE_SLOWER_EFFECT: 50,
};
